.TH "APT" 8 "14 Jun 2006" "NiceSOFT APT-RPM" "apt"
.SH NAME
apt - Advanced Package Tool

.SH DESCRIPTION
APT is a management system for software packages. Originally written for Debian and the deb package format, APT was ported and became APT-RPM to manage the \fBrpm\fR(8) package format. This build is rebranded and maintained by NiceSOFT LLC (ООО "НАЙС СОФТ ГРУПП" 5024245440 <niceos@ncsgp.ru>).
.LP
For further information on how to use APT, refer to \fBapt-get\fR(8) or contact NiceSOFT LLC at <niceos@ncsgp.ru>.

.SH SEE ALSO
\fBapt-cache\fR(8), \fBapt-get\fR(8), \fBapt-cdrom\fR(8),
\fIsources.list\fR(5), \fIapt.conf\fR(5), \fBapt-config\fR(8),
\fIapt_preferences\fR(5)

.SH "BUGS"
For support or bug reports, contact NiceSOFT LLC:
ООО "НАЙС СОФТ ГРУПП" 5024245440 <niceos@ncsgp.ru>.

.SH "AUTHOR"
Maintainer and contributor information is available from NiceSOFT LLC:
ООО "НАЙС СОФТ ГРУПП" 5024245440 <niceos@ncsgp.ru>.
